package ethics

import (
	"github.com/elvisouma/salmar-ai/pkg/models"
)

// ReasoningTransparency provides transparency for AI reasoning processes
type ReasoningTransparency struct {
	// Configuration options
	DetailLevel string // "minimal", "standard", "detailed"
	IncludeConfidence bool
	IncludeModelInfo bool
	IncludeCitations bool
}

// NewReasoningTransparency creates a new reasoning transparency provider
func NewReasoningTransparency() *ReasoningTransparency {
	return &ReasoningTransparency{
		DetailLevel: "standard",
		IncludeConfidence: true,
		IncludeModelInfo: true,
		IncludeCitations: true,
	}
}

// EnhanceTransparency adds transparency information to a response
func (rt *ReasoningTransparency) EnhanceTransparency(response *models.Response, request *models.Request) *models.Response {
	// Add basic reasoning steps if none exist
	if len(response.ReasoningSteps) == 0 {
		response.ReasoningSteps = rt.generateBasicReasoningSteps(request, response)
	}
	
	// Adjust detail level based on configuration
	response.ReasoningSteps = rt.adjustDetailLevel(response.ReasoningSteps)
	
	// Add model information
	if rt.IncludeModelInfo {
		response = rt.addModelInfo(response)
	}
	
	// Add citations if needed
	if rt.IncludeCitations && len(response.Citations) == 0 {
		response = rt.addDefaultCitations(response)
	}
	
	return response
}

// generateBasicReasoningSteps creates basic reasoning steps based on request and response
func (rt *ReasoningTransparency) generateBasicReasoningSteps(request *models.Request, response *models.Response) []models.ReasoningStep {
	steps := []models.ReasoningStep{}
	
	// Add intent classification step
	if request.Intent != "" || response.Intent != "" {
		intent := request.Intent
		if intent == "" {
			intent = response.Intent
		}
		
		steps = append(steps, models.ReasoningStep{
			Description: "Classified user intent as: " + string(intent),
			Confidence:  0.9,
		})
	}
	
	// Add input analysis step based on request mode
	switch request.Mode {
	case models.ModeText:
		steps = append(steps, models.ReasoningStep{
			Description: "Analyzed text input to understand user query",
			Confidence:  0.95,
		})
	case models.ModeImage:
		steps = append(steps, models.ReasoningStep{
			Description: "Analyzed image content to extract relevant information",
			Confidence:  0.85,
		})
	case models.ModeCode:
		steps = append(steps, models.ReasoningStep{
			Description: "Analyzed code structure and functionality",
			Confidence:  0.9,
		})
	case models.ModeMulti:
		steps = append(steps, models.ReasoningStep{
			Description: "Performed integrated analysis of multiple input types",
			Confidence:  0.85,
		})
	}
	
	// Add response generation step
	steps = append(steps, models.ReasoningStep{
		Description: "Generated response based on analysis and user intent",
		Confidence:  0.9,
	})
	
	return steps
}

// adjustDetailLevel modifies reasoning steps based on configured detail level
func (rt *ReasoningTransparency) adjustDetailLevel(steps []models.ReasoningStep) []models.ReasoningStep {
	switch rt.DetailLevel {
	case "minimal":
		// Keep only the most important steps (first and last)
		if len(steps) > 2 {
			return []models.ReasoningStep{steps[0], steps[len(steps)-1]}
		}
		return steps
	case "detailed":
		// Add more detailed descriptions to existing steps
		for i := range steps {
			steps[i].Description = rt.enhanceDescription(steps[i])
		}
		return steps
	default: // "standard"
		// Keep as is, but remove confidence if not needed
		if !rt.IncludeConfidence {
			for i := range steps {
				steps[i].Confidence = 0
			}
		}
		return steps
	}
}

// enhanceDescription adds more detail to step descriptions
func (rt *ReasoningTransparency) enhanceDescription(step models.ReasoningStep) string {
	// This would be more sophisticated in a real implementation
	// Here we just add a prefix for demonstration
	return "Detailed: " + step.Description
}

// addModelInfo adds information about the models used
func (rt *ReasoningTransparency) addModelInfo(response *models.Response) *models.Response {
	if response.ModelInfo == nil {
		response.ModelInfo = make(map[string]interface{})
	}
	
	// Add basic model information
	// In a real implementation, this would include actual model details
	response.ModelInfo["transparency_level"] = rt.DetailLevel
	response.ModelInfo["reasoning_steps_provided"] = len(response.ReasoningSteps) > 0
	
	return response
}

// addDefaultCitations adds placeholder citations when none are provided
func (rt *ReasoningTransparency) addDefaultCitations(response *models.Response) *models.Response {
	// This is a placeholder - in a real implementation, 
	// citations would be generated based on actual sources
	response.Citations = append(response.Citations, models.Citation{
		Text: "This response was generated by Salmar AI",
		URL:  "https://example.com/salmar-ai",
		Title: "Salmar AI System",
	})
	
	return response
}